### ISSUE TITLE
Compared to rehook

### ISSUE THREAD

**Issue by smooJitter** [cevr/arranger#1]
What’s the difference between this and rehook

**Comment by cevr** [comment]
I can see that they follow similar ideas.

However, I think the big selling point of this library is that it's easier to reason about when you compose hooks together.

With rehook, it seems difficult for me to reason about how arrays may work together. But since arranger uses the props object to build upon itself, you can be sure how the data flows down.

For example:
```js
const useEnhancer = pipe(
    // custom arranger hook
    makeStore(state => ({ loadingScope: state.indicators.loadingScope })),
    // custom arranger hook
    makeActions(actions => ({ onLogin: actions.session.onLogin })),
    // custom arranger hook
    makeForm(props => props.onLogin, validate),
    makeProps(props => ({
        inputs: getDefaultInputProps(props),
        hasErrors: Object.keys(props.errors).length === 0 || Object.values(props.errors).some(error => error),
        isLoading: props.loadingScope.includes('Login'),
    })),
);
```
What I wanted to achieve was to make it so it's clear that one hook builds upon the previous

**Comment by smooJitter** [comment]
I see.  In the same way recompose props build upon the previous.  Thank you.
